// Astrologer seed/catalog data for the realtime backend. Mirrors src/data/mockData.ts's
// ASTROLOGERS array at the time the backend was separated from the frontend —
// once a real astrologer-catalog DB table exists, this becomes its seed data
// instead of a duplicated literal.

export const ASTROLOGERS = [
  {
    id: 1,
    name: 'Astrologist Rahul Shastri',
    title: 'Vedic Astrology & Kundli Expert',
    specialization: ['Vedic Astrology', 'Career', 'Finance'],
    rating: 4.9,
    reviews: 3820,
    experience: 14,
    consultations: 12400,
    languages: ['Hindi', 'English'],
    online: true,
    price: 49,
    category: ['Career', 'Finance'],
    avatar: '/images/astrologer-1.jpg',
    badge: 'Top Rated',
    about: 'Specializes in predictive Vedic astrology with deep expertise in Dashas and transits.',
  },
  {
    id: 2,
    name: 'Pandit Meera Devi',
    title: 'Love, Marriage & Relationship Specialist',
    specialization: ['Love', 'Marriage', 'Compatibility'],
    rating: 4.8,
    reviews: 2910,
    experience: 11,
    consultations: 9800,
    languages: ['Hindi', 'Tamil', 'English'],
    online: true,
    price: 39,
    category: ['Love', 'Marriage'],
    avatar: '/images/astrologer-2.jpg',
    badge: 'Highly Recommended',
    about: 'Renowned for her accurate relationship forecasts using Navamsha and synastry techniques.',
  },
  {
    id: 3,
    name: 'Dr. Vikram Joshi',
    title: 'Numerology & Vastu Consultant',
    specialization: ['Numerology', 'Vastu', 'Business'],
    rating: 4.7,
    reviews: 1650,
    experience: 18,
    consultations: 7200,
    languages: ['English', 'Gujarati'],
    online: false,
    price: 59,
    category: ['Vastu', 'Finance'],
    avatar: '/images/astrologer-3.jpg',
    badge: 'Senior Expert',
    about: 'Blends classical Vastu Shastra with modern numerological principles for holistic guidance.',
  },
  {
    id: 4,
    name: 'Jyotishi Ananya Rao',
    title: 'Spiritual Growth & Karma Reader',
    specialization: ['Spirituality', 'Past Life', 'Nakshatras'],
    rating: 4.9,
    reviews: 2200,
    experience: 9,
    consultations: 8100,
    languages: ['Telugu', 'Kannada', 'English'],
    online: true,
    price: 45,
    category: ['Spirituality'],
    avatar: '/images/astrologer-4.jpg',
    badge: 'Rising Star',
    about: 'Combines Nakshatra analysis with spiritual counselling for transformative insights.',
  },
  {
    id: 5,
    name: 'Astrologist Suresh Kumar',
    title: 'Marriage & Family Harmony Expert',
    specialization: ['Marriage', 'Family', 'Kundli Matching'],
    rating: 4.8,
    reviews: 3100,
    experience: 20,
    consultations: 15600,
    languages: ['Hindi', 'Punjabi'],
    online: true,
    price: 55,
    category: ['Marriage', 'Family'],
    avatar: '/images/astrologer-5.jpg',
    badge: 'Expert',
    about: 'With two decades of experience, specializes in Kundli matching and family harmony readings.',
  },
  {
    id: 6,
    name: 'Jyotishi Priya Nair',
    title: 'Career & Business Astrologer',
    specialization: ['Career', 'Business', 'Finance'],
    rating: 4.7,
    reviews: 1890,
    experience: 8,
    consultations: 6400,
    languages: ['Malayalam', 'English'],
    online: false,
    price: 42,
    category: ['Career', 'Finance'],
    avatar: '/images/astrologer-6.jpg',
    badge: 'Verified',
    about: 'Focuses on career trajectory, business timing and financial astrology using Dasha cycles.',
  },
];
